Added Cloud Scheduler to ping Amathus.Reader

diff --git a/Amathus/scripts/config b/Amathus/scripts/config
--- a/Amathus/scripts/config
+++ b/Amathus/scripts/config
@@ -1,19 +1,21 @@
 #!/bin/bash
 
 # Amathus.Web
-if [ "$1" == "web" ]; then
-  SERVICE_SRC=Amathus.Web
-  SERVICE_NAME=amathus-web
-# Amathus.Reader
-elif [ "$1" == "reader" ]; then
-  SERVICE_SRC=Amathus.Reader
-  SERVICE_NAME=amathus-reader
-else
-  echo "Error: No service specified"
-  exit 1
-fi
+set_service() {
+  if [ "$1" == "web" ]; then
+    SERVICE_SRC=Amathus.Web
+    SERVICE_NAME=amathus-web
+  # Amathus.Reader
+  elif [ "$1" == "reader" ]; then
+    SERVICE_SRC=Amathus.Reader
+    SERVICE_NAME=amathus-reader
+  else
+    echo "Error: No service specified"
+    exit 1
+  fi
 
-echo "SERVICE_NAME: $SERVICE_NAME"
-echo "SERVICE_SRC: $SERVICE_SRC"
+  echo "SERVICE_NAME: $SERVICE_NAME"
+  echo "SERVICE_SRC: $SERVICE_SRC"
+}
 
 PROJECT_ID="$(gcloud config get-value core/project)"
